AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS  SAM Template for common resources between NVA stacks


Parameters:
  Suffix:
    Type: String
    Default: ''
    Description: Suffix used for naming resources for feature branches to avoid conflicts.

Conditions:
  WithSuffix: !Not [ !Equals [ !Ref Suffix, '' ] ]
Resources:

  NvaEventsBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !If
        - WithSuffix
        - !Sub 'nva-events-default-bus-${AWS::AccountId}-${Suffix}'
        - !Sub 'nva-events-default-bus-${AWS::AccountId}'

  EventBusArn:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Parameter containing the default EventBridge bus used in NVA so that other services can be aware of the name of the bus.
      Name: /NVA/Events/EventsBusArn
      Type: String
      Value: !GetAtt NvaEventsBus.Arn
  EventBusNamw:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Parameter containing the default EventBridge bus used in NVA so that other services can be aware of the name of the bus.
      Name: /NVA/Events/EventsBusArn
      Type: String
      Value: !GetAtt NvaEventsBus.Name

  EventsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:  !If
        - WithSuffix
        - !Sub 'eventbridge-event-bodies-${AWS::AccountId}-${Suffix}'
        - !Sub 'eventbridge-event-bodies-${AWS::AccountId}'
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: "ExpiryPolicy"
            ExpirationInDays: 1
            NoncurrentVersionExpirationInDays: 1
            Status: Enabled
      VersioningConfiguration:
        Status: Suspended

  EventsBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Parameter containing the bucket name of EventsBucket so that other services can be aware of the name of the bucket.
      Name: /NVA/Events/EventsBucketName
      Type: String
      Value: !Ref EventsBucket
  EventsBucketArn:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Parameter containing the bucket ARN of EventsBucket so that other services can be aware of the name of the bucket.
      Name: /NVA/Events/EventsBucketArn
      Type: String
      Value: !GetAtt EventsBucket.Arn

  #This bucket could belong to the NVA Resources service but being there would
  # prevent us from being able to create and destroy the stack. Also, this bucket is read
  # by the search service, so it is a common resource by definition. The deletion of
  # the NVA Resources service stack should not necessarily break the NVA search service
  ExpandedResourcesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If
        - WithSuffix
        - !Sub 'persisted-resources-${AWS::AccountId}-${Suffix}'
        - !Sub 'persisted-resources-${AWS::AccountId}'
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended

  ExpandedResourcesBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Parameter containing the bucket name of EventsBucket so that other services can be aware of the name of the bucket.
      Name: /NVA/Events/PersistedEntriesBucketName
      Type: String
      Value: !Ref ExpandedResourcesBucket
  ExpandedResourcesBucketArn:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Parameter containing the bucket ARN of EventsBucket so that other services can be aware of the name of the bucket.
      Name: /NVA/Events/PersistedEntriesBucketArn
      Type: String
      Value: !GetAtt ExpandedResourcesBucket.Arn
