AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  SAM Template for common resources between NVA stacks

Metadata:
  AWS::ServerlessRepo::Application:
    Name: NvaCommonResources
    Description: NVA common resources
    Author: Unit
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    Labels: [ '${CODEBUILD_RESOLVED_SOURCE_VERSION}', '${GIT_REPO}', '@${BUILD_TIMESTAMP}' ]

Parameters:
  Suffix:
    Type: String
    Default: ''
    Description: Suffix used for naming resources for feature branches to avoid conflicts.

Conditions:
  WithSuffix: !Not [ !Equals [ !Ref Suffix, '' ] ]
Resources:

  NvaEventsBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !If
        - WithSuffix
        - !Sub 'nva-events-default-bus-${AWS::AccountId}-${Suffix}'
        - !Sub 'nva-events-default-bus-${AWS::AccountId'

  EventsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:  !If
        - WithSuffix
        - !Sub 'eventbridge-event-bodies-${AWS::AccountId}-${Suffix}'
        - !Sub 'eventbridge-event-bodies-${AWS::AccountId'
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: "ExpiryPolicy"
            ExpirationInDays: 10
            NoncurrentVersionExpirationInDays: 10
            Status: Enabled
      VersioningConfiguration:
        Status: Suspended
  EventBusName:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Parameter containing the default EventBridge bus used in NVA so that other services can be aware of the name of the bus.
      Name: /NVA/Events/EventsBusName
      Type: String
      Value: !GetAtt NvaEventsBus.Name
  EventsBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Parameter containing the bucket name of EventsBucket so that other services can be aware of the name of the bucket.
      Name: /NVA/Events/EventsBucketName
      Type: String
      Value: !Ref EventsBucket
  EventsBucketArn:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Parameter containing the bucket ARN of EventsBucket so that other services can be aware of the name of the bucket.
      Name: /NVA/Events/EventsBucketArn
      Type: String
      Value: !GetAtt EventsBucket.Arn

