name: Lint CloudFormation Templates
permissions:
  contents: write # To submit dependency graph
  checks: write # To publish test results
  pull-requests: write # To comment on PRs

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  cloudformation-linter:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup CloudFormation Linter
      uses: scottbrenner/cfn-lint-action@9636da81fb2e0cef75725d8dda11b0148940b7ae #v2.6.0
    - name: Print the Cloud Formation Linter Version & run Linter.
      run: |
        cfn-lint --version
        cfn-lint -t ./template.yaml

    - name: Cloud formation security checks
      uses: stelligent/cfn_nag@master
      with:
        input_path: template.yaml
